# Site settings
title: remkohdev.github.io
email: remkohdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: remkohdev
github_username:  remkohdev

timezone: America/New_York

highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false

# Build settings
markdown: kramdown
source: .
destination: _site