# Site settings
title: remkohdev.github.io
email: remkohdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
twitter_username: remkohdev
github_username:  remkohdev

# Build settings
markdown: kramdown